# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

[uwsgi]
socket = 0.0.0.0:5000
module = invenio_app.wsgi_ui:application
master = true
die-on-term = true
buffer-size = 8192
processes = 2
threads = 2
# TODO: find the reason way log-drain is not working
log-drain = OPTIONS
log-format = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"
single-interpreter = true
