# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

# Extraction from Python source files
[python: **.py]
encoding = utf-8
[python: **/manual_translations.txt]
encoding = utf-8

# Extraction from Jinja2 templates
[jinja2: **/templates/**.html]
encoding = utf-8
extensions = jinja2.ext.do
autoescape = True
silent = False

# Extraction from JavaScript files
[ignore: static/js/rero_ils/admin/**]
[javascript: **.js]
encoding = utf-8
extract_messages = $._, jQuery._

# Extraction from json files (schema, form)
[json: **.json]
keys_to_translate = ['^title$', '^label$', 'description', 'placeholder', 'name', 'add', '403', '.*Message', '^text$']
array_keys_to_translate = ['addon.*']
