# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 RERO.
#
# reroils-app is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
  # es-test:
  #   extends:
  #     file: docker-services.yml
  #     service: es
  #     ports:
  #       - "9200:9200"
  #       - "9300:9300"
  flower:
    extends:
      file: docker-services.yml
      service: flower
    links:
      - mq
