# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-FileCopyrightText: UCLouvain
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Add column to selfcheck_terminals."""

from logging import getLogger

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b90f8b148948"
down_revision = "54134957af7d"
branch_labels = ()
depends_on = None

LOGGER = getLogger("alembic")


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("selfcheck_terminals", sa.Column("comments", sa.Text(), nullable=True))
    LOGGER.info("column added.")
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("selfcheck_terminals", "comments")
    LOGGER.info("column dropped.")
    # ### end Alembic commands ###
