# -*- coding: utf-8 -*-
apiVersion: v1
kind: Service
metadata:
  name: ils-cache
  labels:
    app: ils
    tier: cache
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30015
      name: cache
  selector:
    app: ils
    tier: cache
---
apiVersion: v1
kind: Service
metadata:
  name: ils-db
  labels:
    app: ils
    tier: db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30014
      name: db
  selector:
    app: ils
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: ils-indexer
  labels:
    app: ils
    tier: indexer
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30012
      name: api
    - port: 9300
      nodePort: 30013
      name: cluster
  selector:
    app: ils
    tier: indexer
---
apiVersion: v1
kind: Service
metadata:
  name: ils-mq
  labels:
    app: ils
    tier: mq
spec:
  type: NodePort
  ports:
    - port: 5672
      nodePort: 30017
      name: worker
    - port: 15672
      nodePort: 30016
      name: ui
  selector:
    app: ils
    tier: mq
---
apiVersion: v1
kind: Service
metadata:
  name: ils-tasksui
  labels:
    app: ils
    tier: tasksui
spec:
  type: NodePort
  ports:
    - port: 5555
      nodePort: 30018
  selector:
    app: ils
    tier: tasksui
---
apiVersion: v1
kind: Service
metadata:
  name: ils-frontend
  labels:
    app: ils
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30010
      name: http
    - port: 443
      nodePort: 30011
      name: https
  selector:
    app: ils
    tier: frontend
