# -*- coding: utf-8 -*-
#
# This file is part of RERO ILS.
# Copyright (C) 2017 RERO.
#
# RERO ILS is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RERO ILS is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RERO ILS; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, RERO does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

apiVersion: v1
kind: Pod
metadata:
  name: ils-populate
  labels:
    app: reroils
    tier: populate
spec:
  containers:
  - name: rero-ils
    image: rero/rero-ils:latest
    imagePullPolicy: Always
    command: ["./populate.sh"]
    env:
    - name: PATH
      value: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/reroils/reroils/bin
    - name: GET_HOSTS_FROM
      value: dns
    - name: RABBITMQ_DEFAULT_USER
      valueFrom:
        secretKeyRef:
          name: rero-ils
          key: worker-user
    - name: RABBITMQ_DEFAULT_PASS
      valueFrom:
        secretKeyRef:
          name: rero-ils
          key: worker-password
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: rero-ils
          key: db-user
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: rero-ils
          key: db-name
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rero-ils
          key: db-password
    - name: INVENIO_SEARCH_ELASTIC_HOSTS
      value: ils-indexer:$(ILS_INDEXER_SERVICE_PORT_API)
    - name: INVENIO_SQLALCHEMY_DATABASE_URI
      value: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@ils-db:$(ILS_DB_SERVICE_PORT_DB)/$(POSTGRES_DB)
    - name: INVENIO_CELERY_BROKER_URL
      value: 'amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@ils-worker:$(ILS_WORKER_SERVICE_PORT_WORKER)//'
    - name: INVENIO_CELERY_RESULT_BACKEND
      value: 'redis://ils-cache:$(ILS_CACHE_SERVICE_PORT_CACHE)/1'
    - name: INVENIO_DB_VERSIONING
      value: '0'
    volumeMounts:
    - mountPath: /data
      name: ils-data
  restartPolicy: Never
  volumes:
  - name: ils-data
    hostPath:
      path: /data/docker/reroils
