# Pull base image.
FROM elasticsearch:2.1.1

# Install HEAD plugin
#RUN \
  #plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-aggregations/2.1.1.1/elasticsearch-aggregations-2.1.1.1-plugin.zip \
  #& plugin install karmi/elasticsearch-paramedic/ \
  #& plugin install elasticsearch/elasticsearch-mapper-attachments/3.1.1
#RUN bin/plugin install elasticsearch/elasticsearch-mapper-attachments/3.1.2
#RUN plugin install royrusso/elasticsearch-HQ/2.0.3 \
RUN plugin install elasticsearch/elasticsearch-mapper-attachments/3.1.1
#RUN bin/plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-aggregations/2.1.1.1/elasticsearch-aggregations-2.1.1.1-plugin.zip
RUN plugin install http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-aggregations/2.1.1.1/elasticsearch-aggregations-2.1.1.1-plugin.zip
