# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
RUN bin/elasticsearch-plugin install analysis-icu
