#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# This file is part of RERO ILS.
# Copyright (C) 2017 RERO.
#
# RERO ILS is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# RERO ILS is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RERO ILS; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, RERO does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

set -e


# The real bootstrap script starts 20 lines below ;-)
flags=()
while test $# -gt 0; do
    case "$1" in
        --ci)
            # We are probably inside travis, check for env variables
            if [ "$REQUIREMENTS" == "prod" ]; then
                flags=("--dev" "--ignore-pipfile")
            fi
            shift
            ;;
        *)
            # Use the flags that are passed to the script directly to install
            flags+=("$1")
            shift
            ;;
    esac
done
if [ ${#flags[0]} -eq 0 ]; then
    flags=("--dev" "--skip-lock")
fi

# install the application and all the dependencies
pipenv install ${flags[@]}

# install assets utils
npm update --prefix `pipenv --venv` && npm install --prefix `pipenv --venv` --silent -g node-sass@4.11.0 clean-css@4.2.1 uglify-js@3.4.9 requirejs@2.3.6 @angular/cli@7.1.4


# collect static files and compile html/css assets
CWD=`pwd`
# build the angular ui application
cd ui/admin; npm i; pipenv run npm run deploy

# install the npm dependencies
cd ${CWD}
pipenv run invenio npm
static_folder=$(pipenv run invenio shell --no-term-title -c "print('static_folder:%s' % app.static_folder)"|grep static_folder| cut -d: -f2-)
cd $static_folder
npm install
cd ${CWD}

# build the web assets
pipenv run invenio collect -v
pipenv run invenio assets build
