#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

DIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"
PROGRAM=`basename $0`

set -e

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

install_cypress() {
  info_msg "Install cypress"
  npm install --prefix "tests/e2e/cypress"
}

command_exists () {
    type "$1" &> /dev/null
}

# Displays program name
msg "PROGRAM: ${PROGRAM}"

set -e
export PATH=${PATH}:${DIR}/../tests/e2e/cypress/node_modules/.bin/

# Manage errors with given options
if ! options=$(getopt -o r -l reinstall -- "$@"); then
  error_msg+exit "Error in given options!"
fi

# Manage options
update=false
while test $# -gt 0
do
  case "$1" in
    -r|--reinstall)
      # Update cypress to package.json version
      update=true ;;
    (--) shift; break;;
    (*) break;;
  esac
  shift
done

# Install cypress if not already done
command_exists "cypress" || install_cypress
export CYPRESS_CMD=`which cypress` \
  && info_msg "Found cypress: $(which cypress)"

# Update cypress with -r parameter
if $update ; then
  npm ci --prefix "tests/e2e/cypress"
fi

# Run cypress tests
info_msg "Run e2e tests with cypress"
${CYPRESS_CMD} run -P ./tests/e2e/cypress
