#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

NC='\033[0m'            # Default color
COLORED='\033[1;97;44m' # Bold + white + blue background

set -e

msg() {
  echo -e "${COLORED}${EMPHASIS}[INFO]${NC}${COLORED}: ${1}${NC}" 1>&2
}

msg Dojson ${1}
uv run dojson -i ${1} -l marcxml -d pjson do marc21tojson_rero >${1%.*}.json 2>${1%.*}.log

msg Validate: ${1%.*}.json
uv run invenio reroils utils validate ${1%.*}.json documents document-v0.0.1.json -e ${1%.*}_error.json -o ${1%.*}_ok.json
