#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

# Colored message helpers: msg, info_msg, error_msg, error_msg+exit,
# success_msg, colored_msg.
. "$(dirname "${BASH_SOURCE[0]}")/messages"

PROGRAM=`basename $0`

set -e

# Displays program name
msg "PROGRAM: ${PROGRAM}"

set -e

SCRIPT_PATH=$(dirname "$0")
# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via uv command:\n\tuv run ${PROGRAM}"
fi

if [[ -z "${FLASK_DEBUG}" ]]; then
  export FLASK_DEBUG=True
fi
if [[ -z "${FLASK_ENV}" ]]; then
  export FLASK_ENV="development"
fi

# loglevel: celery log level (Cf. https://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html#cmdoption-celery-worker-l)
# no-worker: disable celery worker
if ! options=$(getopt -o nl: -l no-worker,loglevel: -- "$@"); then
  exit 1
fi

CELERY_LOG_LEVEL="INFO"
worker=true
while test $# -gt 0
do
  case "$1" in
    -l|--loglevel)
      CELERY_LOG_LEVEL=$2
      shift ;;
    -n|--no-worker)
      worker=false ;;
    (--) shift; break;;
    (*) break;;
  esac
  shift
done

# Start Worker and Beat
if $worker; then
  celery --app rero_ils.celery worker --loglevel ${CELERY_LOG_LEVEL} --beat --scheduler rero_ils.schedulers.DatabaseScheduler & PID_CELERY=$!
fi

# Start Server
invenio run \
   --cert "$SCRIPT_PATH"/../docker/nginx/test.crt \
   --key "$SCRIPT_PATH"/../docker/nginx/test.key & PID_SERVER=$!

trap 'kill $PID_CELERY $PID_SERVER &>/dev/null' EXIT

wait $PID_CELERY $PID_SERVER
