#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# RERO ILS
# Copyright (C) 2019 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

DATA_PATH=./data

# Parameters description:
#  --create_items_holdings_small:
#       used for create only the items and holdings files for the 'small' documents file
#  --create_items_holdings_big:
#       used for create only the items and holdings files for the 'big' documents file
#  --deployment:
#       used for deploy the 'big' files
#  --dont_stop:
#       used for continue script on error
#  --time:
#       used for checking time for each command

# COLORS for messages
NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

PROGRAM=`basename $0`

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

invert_warning_option() {
  if ${ENABLE_WARNINGS}
  then
    ENABLE_WARNINGS=false
  else
    ENABLE_WARNINGS=true
  fi
}

create_token() {
  if [ -z ${3} ]
  then
      eval ${PREFIX} invenio reroils utils token-create -n ${1} -u ${2}
  else
      eval ${PREFIX} invenio reroils utils token-create -n ${1} -u ${2} -t ${3}
  fi
}


DEPLOYMENT=false
LOAD_REMOTE_ENTITIES=false
CREATE_ITEMS_HOLDINGS_SMALL=false
CREATE_ITEMS_HOLDINGS_BIG=false
STOP_EXECUTION=true
CREATE_LAZY=""
DONT_STOP=""
PREFIX=""
ES_MAPPING=false
ENQUEUE=""
INDEX_PARALLEL=0
LOADEXTRAFILES=false
# Permit user to set it with system var. Default is true.
ENABLE_WARNINGS=${ENABLE_WARNINGS:=true}
FILES_PATH="${INVENIO_RERO_ILS_FILES_FOLDER:=data/files}"

# Displays program name
msg "PROGRAM: ${PROGRAM}"

# POETRY is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via poetry command:\n\tpoetry run ${PROGRAM}"
fi

# options may be followed by one colon to indicate they have a required argument
if ! options=$(getopt -o dCsbclptmwkD:i: -l deployment,entities,create_items_holdings_small,create_items_holdings_big,lazy,pursue,time,es-mapping,warnings,enqueue,data_path:,index_parallel: -- "$@")
then
    # something went wrong, getopt will put out an error message for us
    exit 1
fi

while [ $# -gt 0 ]
do
    case $1 in
    -d|--deployment)
      DEPLOYMENT=true
      ;;
    -L|--load_extra_files)
      LOADEXTRAFILES=true
      ;;
    -E|--entities)
      LOAD_REMOTE_ENTITIES=true
      ;;
    -s|--create_items_holdings_small)
      CREATE_ITEMS_HOLDINGS_SMALL=true
      ;;
    -b|--create_items_holdings_big)
      CREATE_ITEMS_HOLDINGS_BIG=true
      ;;
    -c|--continue)
      STOP_EXECUTION=false
      ;;
    -l|--lazy)
      CREATE_LAZY="--lazy"
      ;;
    -p|--pursue)
      DONT_STOP="--dont-stop"
      ;;
    -t|--time)
      PREFIX="time"
      ;;  # Get time for all commands
    -m|--es-mapping)
      ES_MAPPING=true
      ;;
    -w|--warnings)
      invert_warning_option
      ;;
    -k|--enqueue)
      ENQUEUE="--enqueue --wait"
      ;;
    -D|--data_path)
      DATA_PATH=$2
      shift
      ;;
    -i|--index_parallel)
      INDEX_PARALLEL=$2
      shift
      ;;
    (--) shift; break;;
    (-*) error_msg+exit "$0: Unrecognized option $1";;
    (*) break;;
    esac
    shift
done

if [[ ! -d "${DATA_PATH}" ]]; then
    error_msg+exit "Error - data path does not exist: ${DATA_PATH}"
fi

if ${CREATE_ITEMS_HOLDINGS_SMALL} && ${CREATE_ITEMS_HOLDINGS_BIG}
then
    error_msg+exit "Choose option for 'small' or 'big' documents generation"
fi

if ${CREATE_ITEMS_HOLDINGS_SMALL} || ${CREATE_ITEMS_HOLDINGS_BIG}
then
    if ${DEPLOYMENT}
    then
        error_msg+exit "Choose deployment option only"
    fi
fi

if ${CREATE_ITEMS_HOLDINGS_BIG}
then
    # set DEPLOYMENT to true in order to use big documents file
    DEPLOYMENT=true
fi

if ! ${ENABLE_WARNINGS}
then
    # Disables different warnings from used applications
    # --------------------------------------------------
    # avoid Python deprecation warnings
    export PYTHONWARNINGS="ignore::DeprecationWarning"
fi

# Purge celery
info_msg "Purge celery"
celery --app rero_ils.celery purge -f
# Clean redis
info_msg "Clean redis"
eval "${PREFIX} invenio shell --no-term-title -c \"import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')\""
eval ${PREFIX} invenio reroils scheduler init -r

info_msg "Prefix: "
info_msg ${PREFIX}

if ${DEPLOYMENT}
then
  eval ${PREFIX} invenio db drop --yes-i-know
  eval ${PREFIX} invenio db create
else
  eval ${PREFIX} invenio db destroy --yes-i-know
  eval ${PREFIX} invenio db init create
fi
eval ${PREFIX} invenio reroils index queue purge
eval ${PREFIX} invenio reroils index queue delete
set -e
eval ${PREFIX} invenio index destroy --force --yes-i-know
eval ${PREFIX} invenio reroils fixtures destroy_operation_logs --yes-i-know

# TODO: check if invenio index init --force works (to delete utils init --force)
info_msg "Override index init to load templates before mapping"
eval ${PREFIX} invenio reroils index init --force
# eval ${PREFIX} invenio index init --force
eval ${PREFIX} invenio reroils index queue init
# Delete invenio_circulations index
info_msg "Delete invenio_circulations index"
eval ${PREFIX} invenio index delete loans-loan-v1.0.0 --force --yes-i-know

info_msg "Initialize files location to ${FILES_PATH}."
eval rm -fr ${FILES_PATH}/*
eval ${PREFIX} invenio files location create --default fixtures ${FILES_PATH}

if ${ES_MAPPING}
then
    info_msg "ES mappings:"
    mkdir -p tmp
    invenio reroils utils dump_es_mappings -o tmp/mapping_before_setup.txt
fi

# create roles
info_msg "Create roles"
eval ${PREFIX} "invenio roles create -d 'Admins Group' admin"
eval ${PREFIX} "invenio roles create -d 'Super Users Group' superuser"
eval ${PREFIX} "invenio roles create -d 'Monitoring Group' monitoring"
eval ${PREFIX} "invenio roles create -d 'Patron' patron"
eval ${PREFIX} "invenio roles create -d 'Professional: Read_only' pro_read_only"
eval ${PREFIX} "invenio roles create -d 'Professional: Acquisition manager' pro_acquisition_manager"
eval ${PREFIX} "invenio roles create -d 'Professional: Full permissions' pro_full_permissions"
eval ${PREFIX} "invenio roles create -d 'Professional: Catalog manager' pro_catalog_manager"
eval ${PREFIX} "invenio roles create -d 'Professional: Circulation manager' pro_circulation_manager"
eval ${PREFIX} "invenio roles create -d 'Professional: Library administrator' pro_library_administrator"
eval ${PREFIX} "invenio roles create -d 'Professional: User manager' pro_user_manager"
eval ${PREFIX} "invenio roles create -d 'Professional: Entity manager' pro_entity_manager"
eval ${PREFIX} "invenio roles create -d 'Documentation Editor' editor"
eval ${PREFIX} "invenio roles create -d 'Document Importing' document_importer"
eval ${PREFIX} "invenio roles create -d 'Professional: Statistics manager' pro_statistic_manager"

info_msg "Create action roles policies"
eval ${PREFIX} "invenio reroils fixtures import_system_role_policies data/system_role_policies.json"
eval ${PREFIX} "invenio reroils fixtures import_role_policies data/role_policies.json"

# create users
info_msg "Create users"
eval ${PREFIX} invenio users create --active --confirm --password administrator admin@rero.ch
eval ${PREFIX} invenio users create --active --confirm --password editor editor@rero.ch
eval ${PREFIX} invenio users create --active --confirm --password monitor monitoring@rero.ch
eval ${PREFIX} invenio users create --active --confirm --password ngscan gipi@ngscan.com

# grant accesses to action roles
info_msg "Grant access to action roles"
eval ${PREFIX} invenio access allow superuser-access role admin
eval ${PREFIX} invenio access allow superuser-access role superuser
eval ${PREFIX} invenio access allow admin-access role admin

# grant roles to users
info_msg "Grant roles to users"
eval ${PREFIX} invenio roles add admin@rero.ch admin
eval ${PREFIX} invenio roles add admin@rero.ch superuser
eval ${PREFIX} invenio roles add admin@rero.ch monitoring
eval ${PREFIX} invenio roles add editor@rero.ch editor
eval ${PREFIX} invenio roles add monitoring@rero.ch monitoring
eval ${PREFIX} invenio roles add gipi@ngscan.com document_importer

# create token access for monitoring
info_msg "Create token for: monitoring@rero.ch"
create_token monitoring monitoring@rero.ch ${INVENIO_RERO_ACCESS_TOKEN_MONITORING}
# create token access for ngscan (ezpump)
info_msg "Create token for: gipi@ngscan.com"
create_token ezpump gipi@ngscan.com ${INVENIO_RERO_ACCESS_TOKEN_NGSCAN}

# Generate fixtures
info_msg "Generate fixtures:"

info_msg "- Organisations ${DATA_PATH}/organisations.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type org ${DATA_PATH}/organisations.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t org --yes-i-know

info_msg "- Libraries: ${DATA_PATH}/libraries.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type lib ${DATA_PATH}/libraries.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t lib --yes-i-know

info_msg "- Locations: ${DATA_PATH}/locations.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type loc ${DATA_PATH}/locations.json  --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t loc --yes-i-know

info_msg "- Item types: ${DATA_PATH}/item_types.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type itty ${DATA_PATH}/item_types.json  --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t itty --yes-i-know

info_msg "- Patron types: ${DATA_PATH}/patron_types.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type ptty ${DATA_PATH}/patron_types.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t ptty --yes-i-know

info_msg "- Circulation policies: ${DATA_PATH}/circulation_policies.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type cipo ${DATA_PATH}/circulation_policies.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t cipo --yes-i-know

info_msg "Acquisition vendors: ${DATA_PATH}/vendors.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type vndr ${DATA_PATH}/vendors.json --append  ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t vndr --yes-i-know

if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
fi
eval ${PREFIX} invenio reroils index run --raise-on-error
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t org -t lib -t loc -t itty -t ptty -t cipo -t vndr -v
fi

info_msg "- Users: ${DATA_PATH}/users.json"
eval ${PREFIX} invenio reroils fixtures import_users ${DATA_PATH}/users.json -v --append ${CREATE_LAZY} ${DONT_STOP}

info_msg "- ILL requests: ${DATA_PATH}/ill_request.json"
eval ${PREFIX} invenio reroils fixtures create_ill_requests -f ${DATA_PATH}/ill_requests.json
eval ${PREFIX} invenio reroils index reindex -t illr --yes-i-know

info_msg "- Statistics configurations: ${DATA_PATH}/stats_cfg.json"
eval ${PREFIX} invenio reroils fixtures create --pid_type stacfg ${DATA_PATH}/stats_cfg.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t stacfg --yes-i-know

info_msg "- Local entities ${DATA_PATH}/local_entities.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type locent --schema 'https://bib.rero.ch/schemas/local_entities/local_entity-v0.0.1.json' ${DATA_PATH}/local_entities.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t locent --yes-i-know
eval ${PREFIX} invenio reroils index run --raise-on-error

#: - xml to json transformation for rero marcxml --------------------------------
#: don't forget to recreat the documents json schema files:
# SIZE=big # SIZE=small
# export RERO_ILS_MEF_AGENTS_URL=https://mef.rero.ch/api/agents
# invenio reroils utils marc21tojson -t rero ${DATA_PATH}/documents_${SIZE}.xml ${DATA_PATH}/documents_${SIZE}.json ${DATA_PATH}/documents_${SIZE}_errors.xml -v -r
# Save the entities after setup for later use.
# invenio reroils utils export -t rement -o ${DATA_PATH}/remote_entities_${SIZE}.json -v

if ${DEPLOYMENT}
then
    DOCUMENTS=${DATA_PATH}/documents_big.json
    ITEMS=${DATA_PATH}/items_big.json
    HOLDINGS=${DATA_PATH}/holdings_big.json
    REMOTE_ENTITIES=${DATA_PATH}/remote_entities_big.json
else
    DOCUMENTS=${DATA_PATH}/documents_small.json
    ITEMS=${DATA_PATH}/items_small.json
    HOLDINGS=${DATA_PATH}/holdings_small.json
    REMOTE_ENTITIES=${DATA_PATH}/remote_entities_small.json
fi

if ${LOAD_REMOTE_ENTITIES}
then
    info_msg "- REMOTE REMOTE_ENTITIES: ${REMOTE_ENTITIES} ${CREATE_LAZY} ${DONT_STOP}"
    eval ${PREFIX} invenio reroils fixtures create --pid_type rement --schema 'https://bib.rero.ch/schemas/remote_entities/remote_entity-v0.0.1.json' ${REMOTE_ENTITIES} --append ${CREATE_LAZY} ${DONT_STOP}
    info_msg "Indexing Entities:"
    eval ${PREFIX} invenio reroils index reindex -t rement --yes-i-know
    if [ ${INDEX_PARALLEL} -gt 0 ]; then
        eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
    fi
    eval ${PREFIX} invenio reroils index run --raise-on-error
    if [ ${INDEX_PARALLEL} -gt 0 ]; then
        eval ${PREFIX} invenio reroils index reindex_missing -t rement -v
    fi
# else
#     info_msg "- Contributions from MEF: ${DOCUMENTS} ${CREATE_LAZY} ${ENQUEUE}"
#     eval ${PREFIX} invenio reroils fixtures get_all_mef_records ${DOCUMENTS} ${CREATE_LAZY} ${ENQUEUE} -v
fi

info_msg "- Documents: ${DOCUMENTS} ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type doc --schema 'https://bib.rero.ch/schemas/documents/document-v0.0.1.json' ${DOCUMENTS} --append ${CREATE_LAZY} ${DONT_STOP}

if ${CREATE_ITEMS_HOLDINGS_SMALL}
then
    # to generate small items file small documents must exist in DB
    msg "\tSMALL documents, creation of items and holdings"
    eval ${PREFIX} invenio reroils fixtures create_items -i 3 -t ${DATA_PATH}/items_small.json -h ${DATA_PATH}/holdings_small.json
    success_msg "Creation of items and holdings done for 'small' documents."
    if ${STOP_EXECUTION}
    then
        exit 0
    fi
fi

if ${CREATE_ITEMS_HOLDINGS_BIG}
then
    # to generate big items file big documents must exist in DB
    msg "\tBIG documents, creation of items and holdings"
    eval ${PREFIX} invenio reroils fixtures create_items -i 3 -t ${DATA_PATH}/items_big.json -h ${DATA_PATH}/holdings_big.json
    success_msg "Creation of items and holdings done for 'big' documents."
    if ${STOP_EXECUTION}
    then
        exit 0
    fi
fi

info_msg "- Holdings: ${HOLDINGS} ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type hold --schema 'https://bib.rero.ch/schemas/holdings/holding-v0.0.1.json' ${HOLDINGS} --append ${CREATE_LAZY} ${DONT_STOP}


info_msg "- Items: ${ITEMS} ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type item --schema 'https://bib.rero.ch/schemas/items/item-v0.0.1.json' ${ITEMS} --append ${CREATE_LAZY} ${DONT_STOP}

info_msg "- Generate files"
eval ${PREFIX} invenio reroils fixtures create-files 75

# index items
eval ${PREFIX} invenio reroils index reindex -t item --yes-i-know
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
fi
eval ${PREFIX} invenio reroils index run --raise-on-error
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t item -v
fi

# index holdings
eval ${PREFIX} invenio reroils index reindex -t hold --yes-i-know
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
fi
eval ${PREFIX} invenio reroils index run --raise-on-error
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t hold -v
fi

# index documents
eval ${PREFIX} invenio reroils index reindex -t doc --yes-i-know
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
fi
eval ${PREFIX} invenio reroils index run --raise-on-error
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t doc -v
fi

# index entities
# We have to reindex entities to get the organisations pids indexed correctly.
eval ${PREFIX} invenio reroils index reindex -t rement --yes-i-know
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
fi
eval ${PREFIX} invenio reroils index run --raise-on-error
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t rement -v
fi

info_msg "- Local fields ${DATA_PATH}/local_fields.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type lofi ${DATA_PATH}/local_fields.json --append ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t lofi --yes-i-know

# create serials patterns
info_msg "Serials patterns: ${DATA_PATH}/patterns.json"
eval ${PREFIX} invenio reroils fixtures create_patterns ${DATA_PATH}/patterns.json

info_msg "- Collections: ${DATA_PATH}/collections.json"
eval ${PREFIX} invenio reroils fixtures create_collections -f ${DATA_PATH}/collections.json
eval ${PREFIX} invenio reroils index reindex -t coll --yes-i-know
eval ${PREFIX} invenio reroils index run --raise-on-error

# # ACQUISITION
# create library budgets
info_msg "Library budgets: ${DATA_PATH}/budgets.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type budg ${DATA_PATH}/budgets.json --append  ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -d -t budg --yes-i-know
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t budg -v
fi
# create acquisition accounts
info_msg "Acquisition accounts: ${DATA_PATH}/acq_accounts.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type acac ${DATA_PATH}/acq_accounts.json --append  --reindex ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -d -t acac --yes-i-know

# create acquisition orders
info_msg "Acquisition orders: ${DATA_PATH}/acq_orders.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type acor ${DATA_PATH}/acq_orders.json --append  --reindex ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -d -t acor --yes-i-know

# create acquisition order lines
info_msg "Acquisition order lines: ${DATA_PATH}/acq_order_lines.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type acol ${DATA_PATH}/acq_order_lines.json --append  --reindex ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -d -t acol --yes-i-know

# reindex acquisition orders to receive the correct status
# eval ${PREFIX} invenio reroils index reindex -d -t acor --yes-i-know

# create acquisition receipts
info_msg "Acquisition receipts: ${DATA_PATH}/acq_receipts.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type acre ${DATA_PATH}/acq_receipts.json --append  --reindex ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -d -t acre --yes-i-know

# create acquisition receipt lines
info_msg "Acquisition receipt lines: ${DATA_PATH}/acq_receipt_lines.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create --pid_type acrl ${DATA_PATH}/acq_receipt_lines.json --append  --reindex ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -d -t acrl --yes-i-know

# create resource templates
info_msg "Resource templates:"
eval ${PREFIX} invenio reroils fixtures create --pid_type tmpl ${DATA_PATH}/templates.json --append  ${CREATE_LAZY} ${DONT_STOP}
eval ${PREFIX} invenio reroils index reindex -t tmpl --yes-i-know

if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
fi
eval ${PREFIX} invenio reroils index run --raise-on-error
if [ ${INDEX_PARALLEL} -gt 0 ]; then
    eval ${PREFIX} invenio reroils index reindex_missing -t lofi -t coll -t acac -t acol -t tmpl -t acor -v
fi


if ${LOADEXTRAFILES}
  then
      # create acquisition invoices
      info_msg "Acquisition invoices: ${DATA_PATH}/acq_invoices.json ${CREATE_LAZY} ${DONT_STOP}"
      eval ${PREFIX} invenio reroils fixtures create --pid_type acin ${DATA_PATH}/acq_invoices.json --append  --reindex ${CREATE_LAZY} ${DONT_STOP}
      eval ${PREFIX} invenio reroils index reindex -t acin --yes-i-know
      if [ ${INDEX_PARALLEL} -gt 0 ]; then
          eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
      fi
      eval ${PREFIX} invenio reroils index run --raise-on-error

      if [ ${INDEX_PARALLEL} -gt 0 ]; then
          eval ${PREFIX} invenio reroils index reindex_missing -t acre -t acrl -t acin -v
      fi

      # reindex acquisition order lines
      eval ${PREFIX} invenio reroils index reindex -t acol --yes-i-know
      if [ ${INDEX_PARALLEL} -gt 0 ]; then
          eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
      fi
      eval ${PREFIX} invenio reroils index run --raise-on-error

      # reindex acquisition orders
      eval ${PREFIX} invenio reroils index reindex -t acor --yes-i-know
      if [ ${INDEX_PARALLEL} -gt 0 ]; then
          eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
      fi
      eval ${PREFIX} invenio reroils index run --raise-on-error

      # reindex acquisition accounts
      eval ${PREFIX} invenio reroils index reindex -t acac --yes-i-know
      if [ ${INDEX_PARALLEL} -gt 0 ]; then
          eval ${PREFIX} invenio reroils index run -d -c ${INDEX_PARALLEL} --raise-on-error
      fi
      eval ${PREFIX} invenio reroils index run --raise-on-error

  fi


# create circulation transactions
info_msg "Circulation transactions: ${DATA_PATH}/loans.json ${CREATE_LAZY} ${DONT_STOP}"
eval ${PREFIX} invenio reroils fixtures create_loans ${DATA_PATH}/loans.json -v

# process notifications
eval ${PREFIX} invenio reroils notifications process

# create token access for system librarians
info_msg "create an access token for all system librarians"
create_token organisation_aosta_token reroilstest@gmail.com ${INVENIO_RERO_ACCESS_TOKEN_AOSTA_LIBRARIAN}
create_token organisation_scotland_token reroilstest+irma@gmail.com  ${INVENIO_RERO_ACCESS_TOKEN_SCOLAND_LIBRARIAN}
create_token organisation_fictive_token reroilstest+imagination@gmail.com ${INVENIO_RERO_ACCESS_TOKEN_FICTIVE_LIBRARIAN}

# # OAI configuration
info_msg "OAI configuration: ${DATA_PATH}/oaisources.yml"
eval ${PREFIX} invenio reroils oaiharvester initconfig ${DATA_PATH}/oaisources.yml

eval ${PREFIX} invenio reroils scheduler enable_tasks -a -v
# disable ebook harvesting
eval ${PREFIX} invenio reroils scheduler enable_tasks -n ebooks-harvester -d

if ${DEPLOYMENT}
then
    # start oai harvesting asynchrone: beats must be running
    info_msg "Start OAI harvesting asynchrone"
    eval ${PREFIX} invenio reroils oaiharvester harvest -n ebooks -a max=150 -q -k
else
    info_msg "For ebooks harvesting run:"
    msg "\tinvenio reroils oaiharvester harvest -n ebooks -a max=100 -q"
fi

if ${ES_MAPPING}
then
    info_msg "ES mappings:"
    invenio reroils utils dump_es_mappings -o tmp/mapping_after_setup.txt
    error_msg "ES mapping differences:"
    diff --suppress-common-lines --side-by-side tmp/mapping_before_setup.txt tmp/mapping_after_setup.txt
fi

if ${LOADEXTRAFILES}
  then
    info_msg "- Load Virtua operation logs: ${DATA_PATH}/operation_logs.json"
    eval ${PREFIX} invenio reroils fixtures create_operation_logs ${DATA_PATH}/operation_logs.json  ${CREATE_LAZY} ${DONT_STOP}

    # load legacy circulation transactions from Virtua
    info_msg "Checkout transactions: ${DATA_PATH}/checkouts.json ${CREATE_LAZY} ${DONT_STOP}"
    eval ${PREFIX} invenio reroils fixtures load_virtua_transactions ${DATA_PATH}/checkouts.json -t checkout

    info_msg "Request transactions: ${DATA_PATH}/requests.json ${CREATE_LAZY} ${DONT_STOP}"
    eval ${PREFIX} invenio reroils fixtures load_virtua_transactions ${DATA_PATH}/requests.json -t request

    info_msg "Fine transactions: ${DATA_PATH}/fines.json ${CREATE_LAZY} ${DONT_STOP}"
    eval ${PREFIX} invenio reroils fixtures load_virtua_transactions ${DATA_PATH}/fines.json -t fine
fi

info_msg "Collect statistics"
eval ${PREFIX} invenio reroils stats collect billing
eval ${PREFIX} invenio reroils stats collect librarian
eval ${PREFIX} invenio reroils stats report collect-all month
eval ${PREFIX} invenio reroils stats report collect-all year

info_msg "Initialize wiki search"
eval ${PREFIX} invenio flask_wiki init-index
eval ${PREFIX} invenio flask_wiki index

date
success_msg "Perfect ${PROGRAM}! See you soon…"
exit 0
