#!/usr/bin/env bash
# SPDX-FileCopyrightText: Fondation RERO+
# SPDX-License-Identifier: AGPL-3.0-or-later

# COLORS for messages
NC='\033[0m'                    # Default color
INFO_COLOR='\033[1;97;44m'      # Bold + white + blue background
SUCCESS_COLOR='\033[1;97;42m'   # Bold + white + green background
ERROR_COLOR='\033[1;97;41m'     # Bold + white + red background

PROGRAM=`basename $0`
SCRIPT_PATH=$(dirname "$0")

# MESSAGES
msg() {
  echo -e "${1}" 1>&2
}
# Display a colored message
# More info: https://misc.flogisoft.com/bash/tip_colors_and_formatting
# $1: choosen color
# $2: title
# $3: the message
colored_msg() {
  msg "${1}[${2}]: ${3}${NC}"
}

info_msg() {
  colored_msg "${INFO_COLOR}" "INFO" "${1}"
}

error_msg() {
  colored_msg "${ERROR_COLOR}" "ERROR" "${1}"
}

error_msg+exit() {
    error_msg "${1}" && exit 1
}

success_msg() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}"
}

success_msg+exit() {
  colored_msg "${SUCCESS_COLOR}" "SUCCESS" "${1}" && exit 0
}

pip_audit_exceptions=""
add_exceptions() {
  pip_audit_exceptions="$pip_audit_exceptions --ignore-vuln $1"""
}

# Displays program name
msg "PROGRAM: ${PROGRAM}"

# uv is a mandatory condition to launch this program!
if [[ -z "${VIRTUAL_ENV}" ]]; then
  error_msg+exit "Error - Launch this script via uv command:\n\t${PROGRAM}"
fi

function pretests () {
  info_msg "Check vulnerabilities:"
  # pytest needs to be updated by pytest-invenio
  # pytest 8.4.2   CVE-2025-71176 9.0.3
  add_exceptions "CVE-2025-71176"
  # flask-cors 6.0.2   PYSEC-2024-271 (no fix version available)
  add_exceptions "PYSEC-2024-271"
  # markdown 3.10.2    PYSEC-2026-89  (no fix version available)
  add_exceptions "PYSEC-2026-89"
  # pyjwt 2.12.1       PYSEC-2025-183 (no fix version available)
  add_exceptions "PYSEC-2025-183"
  pip-audit ${pip_audit_exceptions}

  info_msg "Check json:"
  invenio reroils utils check_json tests/data rero_ils/modules data
  info_msg "Check license headers:"
  invenio reroils utils check_license
  info_msg "Test formatting:"
  ruff format --check rero_ils tests
  info_msg "Test linting:"
  ruff check rero_ils tests
}

function tests () {
  info_msg "Tests All:"
  pytest
}

function tests_api () {
  info_msg "Tests API:"
  pytest ./tests/api
}
function tests_e2e () {
  info_msg "Tests E2E:"
  pytest ./tests/e2e
}
function tests_scheduler () {
  info_msg "Tests Scheduler:"
  pytest ./tests/scheduler
}
function tests_ui () {
  info_msg "Tests UI:"
  pytest ./tests/ui
}
function tests_unit () {
  info_msg "Tests Unit:"
  pytest ./tests/unit
}
function tests_external () {
  info_msg "Tests External:"
  pytest tests/api/test_external_services.py
}
function tests_other () {
  info_msg "Tests Other:"
  pytest ./tests/conftest.py ./tests/test_version.py ./tests/utils.py
}

if [ $# -eq 0 ]
  then
    set -e
    pretests
    tests
fi

if [ "$1" = "other" ]
  then
    set -e
    pretests
    tests_other
fi
if [ "$1" = "api" ]
  then
    set -e
    tests_api
fi
if [ "$1" = "e2e" ]
  then
    set -e
    tests_e2e
fi
if [ "$1" = "scheduler" ]
  then
    set -e
    tests_scheduler
fi
if [ "$1" = "ui" ]
  then
    set -e
    tests_ui
fi
if [ "$1" = "unit" ]
  then
    set -e
    tests_unit
fi
if [ "$1" = "external" ]
  then
    set -e
    tests_external
fi

success_msg+exit "Perfect ${PROGRAM} external! See you soon…"
