#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 RERO.
#
# reroils-app is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")
./"$script_path"/bootstrap

invenio alembic upgrade
invenio index init --force
