# -*- coding: utf-8 -*-
#
# RERO ILS
# Copyright (C) 2019 RERO
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

"""Test explain."""


from rero_ils.modules.sru.explaine import Explain


def test_explain(app):
    """Test Explain."""
    explain = Explain('api/sru')
    assert explain.indexes == [
        'pid',
        'title.type',
        'authorized_access_point',
        'autocomplete_title',
        'sort_title',
        'responsibilityStatement.value',
        'responsibilityStatement.language',
        'titlesProper',
        'type.main_type',
        'type.subtype',
        'language.type',
        'language.value',
        'issuance.main_type',
        'issuance.subtype',
        'partOf.document.type',
        'partOf.document.pid',
        'partOf.numbering.year',
        'partOf.numbering.volume',
        'partOf.numbering.issue',
        'partOf.numbering.pages',
        'translatedFrom',
        'contribution.agent.type',
        'contribution.agent.pid',
        'contribution.agent.authorized_access_point_en',
        'contribution.agent.authorized_access_point_fr',
        'contribution.agent.authorized_access_point_de',
        'contribution.agent.authorized_access_point_it',
        'contribution.agent.authorized_access_point',
        'contribution.agent.variant_access_point',
        'contribution.agent.parallel_access_point',
        'contribution.agent.preferred_name',
        'contribution.role',
        'facet_contribution_en',
        'facet_contribution_fr',
        'facet_contribution_de',
        'facet_contribution_it',
        'copyrightDate',
        'editionStatement._text.value',
        'editionStatement._text.language',
        'electronicLocator.publicNote',
        'electronicLocator.content',
        'electronicLocator.type',
        'electronicLocator.url',
        'provisionActivity.place.identifiedBy.type',
        'provisionActivity.place.identifiedBy.source',
        'provisionActivity.place.identifiedBy.value',
        'provisionActivity._text.value',
        'provisionActivity._text.language',
        'extent',
        'bookFormat',
        'dimensions',
        'illustrativeContent',
        'colorContent',
        'productionMethod',
        'duration',
        'series._text',
        'seriesStatement._text.value',
        'seriesStatement._text.language',
        'note.label',
        'note.noteType',
        'abstracts',
        'identifiedBy.type',
        'identifiedBy.source',
        'identifiedBy.value',
        'identifiedBy.note',
        'identifiedBy.qualifier',
        'identifiedBy.acquisitionTerms',
        'identifiedBy.status',
        'subjects.type',
        'subjects.preferred_name',
        'subjects.term',
        'subjects.title',
        'subjects.creator',
        'subjects.conference',
        'subjects.identifiedBy.type',
        'subjects.identifiedBy.source',
        'subjects.identifiedBy.value',
        'subjects.source',
        'facet_subjects',
        'subjects_imported.type',
        'subjects_imported.preferred_name',
        'subjects_imported.term',
        'subjects_imported.title',
        'subjects_imported.creator',
        'subjects_imported.conference',
        'subjects_imported.identifiedBy.type',
        'subjects_imported.identifiedBy.source',
        'subjects_imported.identifiedBy.value',
        'subjects_imported.source',
        'holdings.pid',
        'holdings.available',
        'holdings.location.pid',
        'holdings.circulation_category.pid',
        'holdings.circulation_category.type',
        'holdings.organisation.organisation_pid',
        'holdings.organisation.library_pid',
        'holdings.local_fields.organisation_pid',
        'holdings.local_fields.fields.field_1',
        'holdings.local_fields.fields.field_2',
        'holdings.local_fields.fields.field_3',
        'holdings.local_fields.fields.field_4',
        'holdings.local_fields.fields.field_5',
        'holdings.local_fields.fields.field_6',
        'holdings.local_fields.fields.field_7',
        'holdings.local_fields.fields.field_8',
        'holdings.local_fields.fields.field_9',
        'holdings.local_fields.fields.field_10',
        'holdings.call_number',
        'holdings.second_call_number',
        'holdings.index',
        'holdings.enumerationAndChronology',
        'holdings.supplementaryContent',
        'holdings.notes',
        'holdings.items.pid',
        'holdings.items.barcode',
        'holdings.items.call_number',
        'holdings.items.status',
        'holdings.items.available',
        'holdings.items.acquisition.organisation_pid',
        'holdings.items.acquisition.library_pid',
        'holdings.items.acquisition.location_pid',
        'holdings.items.acquisition.date',
        'holdings.items.notes',
        'holdings.items.collections.title',
        'holdings.items.collections.description',
        'holdings.items.local_fields.organisation_pid',
        'holdings.items.local_fields.fields.field_1',
        'holdings.items.local_fields.fields.field_2',
        'holdings.items.local_fields.fields.field_3',
        'holdings.items.local_fields.fields.field_4',
        'holdings.items.local_fields.fields.field_5',
        'holdings.items.local_fields.fields.field_6',
        'holdings.items.local_fields.fields.field_7',
        'holdings.items.local_fields.fields.field_8',
        'holdings.items.local_fields.fields.field_9',
        'holdings.items.local_fields.fields.field_10',
        'local_fields.organisation_pid',
        'local_fields.fields.field_1',
        'local_fields.fields.field_2',
        'local_fields.fields.field_3',
        'local_fields.fields.field_4',
        'local_fields.fields.field_5',
        'local_fields.fields.field_6',
        'local_fields.fields.field_7',
        'local_fields.fields.field_8',
        'local_fields.fields.field_9',
        'local_fields.fields.field_10',
        'supplement.label',
        'supplementTo.label',
        'otherEdition.label',
        'otherPhysicalFormat.label',
        'issuedWith.label',
        'precededBy.label',
        'succeededBy.label',
        'relatedTo.label',
        'intendedAudience.audienceType',
        'intendedAudience.value',
        'summary.source',
        'summary.label.value',
        'summary.label.language',
        'originalLanguage',
        'frequency.label',
        'frequency.date',
        'originalTitle',
        'classification.type',
        'classification.classificationPortion',
        'classification.subdivision',
        'classification.edition',
        'classification.assigner',
        'sequence_numbering',
        'dissertation.label.value',
        'dissertation.label.language',
        'contentMediaCarrier.contentType',
        'contentMediaCarrier.mediaType',
        'contentMediaCarrier.carrierType',
        'credits',
        'supplementaryContent',
        'acquisitionTerms',
        'tableOfContents',
        'temporalCoverage.type',
        'temporalCoverage.date',
        'temporalCoverage.start_date',
        'temporalCoverage.end_date',
        'temporalCoverage.period_code',
        'genreForm.type',
        'genreForm.term',
        'genreForm.identifiedBy.type',
        'genreForm.identifiedBy.source',
        'genreForm.identifiedBy.value',
        'genreForm.source',
        'genreForm_imported.type',
        'genreForm_imported.term',
        'genreForm_imported.identifiedBy.type',
        'genreForm_imported.identifiedBy.source',
        'genreForm_imported.identifiedBy.value',
        'genreForm_imported.source',
        'adminMetadata.note',
        'adminMetadata.encodingLevel',
        'adminMetadata.source',
        'adminMetadata.descriptionModifier',
        'adminMetadata.descriptionLanguage',
        'adminMetadata.descriptionConventions',
        'scale.type',
        'scale.label',
        'scale.ratio_linear_horizontal',
        'scale.ratio_linear_vertical',
        'cartographicAttributes.coordinates.label',
        'cartographicAttributes.coordinates.longitude',
        'cartographicAttributes.coordinates.latitude',
        'cartographicAttributes.coordinates.declination',
        'cartographicAttributes.coordinates.rightAscension',
        'cartographicAttributes.projection',
        'cartographicAttributes.equinox',
        'work_access_point.title',
        'work_access_point.date_of_work',
        'work_access_point.miscellaneous_information',
        'work_access_point.language',
        'work_access_point.part.partNumber',
        'work_access_point.part.partName',
        'work_access_point.form_subdivision',
        'work_access_point.medium_of_performance_for_music',
        'work_access_point.arranged_statement_for_music',
        'work_access_point.key_for_music',
        'usageAndAccessPolicy.type',
        'usageAndAccessPolicy.label',
        'available',
        'organisation.type',
        'organisation.pid',
        'status',
        'harvested',
        'isbn',
        '_draft',
        '_masked',
        '_created',
        '_updated'
    ]
    explain_strings = str(explain).split('\n')
    assert explain_strings[0] == \
        '<sru:explainResponse xmlns:sru="http://www.loc.gov/standards/sru/">'
